// This file is auto-generated by scripts/generate-media-manifest.js
const mediaFilesList = [
  "./images/image1.png",
  "./images/image2.png",
  "./video/video1.mp4"
];

export const mediaFiles = Object.freeze(mediaFilesList);
