// This file is auto-generated by scripts/generate-media-manifest.js
const mediaFilesList = [
  "./images/image%20(1).png",
  "./images/image%20(2).png",
  "./video/video%20(1).mp4"
];

export const mediaFiles = Object.freeze(mediaFilesList);
